# Generated by Django 4.2.17 on 2024-12-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="file_text",
            field=models.TextField(default="No text extracted"),
        ),
        migrations.AddField(
            model_name="video",
            name="transcription",
            field=models.TextField(default="No text extracted"),
        ),
    ]
