# Generated by Django 4.2.17 on 2024-12-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0002_note_file_text_video_transcription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="notes/"),
        ),
    ]
