# Generated by Django 4.2.17 on 2024-12-11 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0003_alter_note_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Note",
            new_name="Notes",
        ),
    ]
