# Generated by Django 4.2.17 on 2024-12-11 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0004_rename_note_notes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Video",
            new_name="Videos",
        ),
    ]
